###

GET http://localhost:3000/users


###

GET http://localhost:3000/users/3



###

POST http://localhost:3000/users
Content-Type: application/json

{
    "id": "5",
    "name": "Shoham Moyal",
    "email": "moyal.shoham@gmail.com",
    "password": "Shoham123",
    "age": 25
}



###

PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "id": "1",
  "age": 26,
  "password": "Shoham123",
  "email": "moyal.shoham@gmail.com",
  "name": "Shoham Moyal"

}


###

DELETE http://localhost:3000/users/1



###

GET http://localhost:3000/posts


###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner": "5",
    "title": "test",
    "content": "test",
    "published": true
}




###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "tesst@gmail.com",
    "password": "Shoham123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "tesst@gmail.com",
    "password": "Shoham123"
}


###

POST http://localhost:3000/users/post-file
Content-Type: application/json

{
    
}

###

GET http://localhost:3000/auth/logout



###

GET http://localhost:3000/users/get-files


###

PUT http://localhost:3000/users/update-user-full-name
Content-Type: application/json

{
    "id": "RZZi09fpNVP8ibGHCOyvRE80dOj2",
    "name": "Shoham Moyal"
}